[server]
headless = true
maxUploadSize = 80
fileWatcherType = "none"
enableCORS = true
enableXsrfProtection = true
xsrfCookieSameSite = "none"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#1A4A6E"
backgroundColor = "#F4F6F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0C1929"
font = "sans serif"
